version: '3'
services:
  flask-container:
    container_name: flask-container
    image: public.ecr.aws/n2w0j8l6/employee-flask:latest
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      MYSQL_HOST: mysql-container
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: "*snuggy_14"
      MYSQL_DATABASE: flask_app_db

  mysql-container:
    container_name: mysql-container
    image: public.ecr.aws/n2w0j8l6/mysql_db:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: "*snuggy_14"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: